# Generated by Django 2.1.2 on 2018-11-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, unique=True)),
                ('article_content', models.TextField()),
                ('publish_date', models.DateTimeField(default='2018-11-26 18:13:01')),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('title', models.CharField(max_length=30)),
                ('article_url', models.URLField()),
                ('alt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=10)),
                ('sub_industry_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女'), ('other', '其他')], default=('男',), max_length=6)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WechatAccount',
            fields=[
                ('wechat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wechat_name', models.CharField(max_length=50)),
                ('head_portrait', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wechat_account',
            },
        ),
        migrations.CreateModel(
            name='WeChatArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.CharField(max_length=20)),
                ('article_title', models.CharField(max_length=100)),
                ('article_url', models.TextField()),
                ('cover_img', models.TextField()),
                ('article_content', models.TextField()),
                ('article_html', models.TextField()),
                ('img_amount', models.IntegerField(default='0')),
                ('word_amount', models.IntegerField(default='0')),
                ('video_amount', models.IntegerField(default='0')),
                ('audio_amount', models.IntegerField(default='0')),
                ('wechat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WechatAccount')),
            ],
            options={
                'db_table': 'wechat_article',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wechataccount',
            unique_together={('wechat_id',)},
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='wechatarticle',
            unique_together={('publish_date', 'article_title')},
        ),
    ]
