# Generated by Django 2.1.2 on 2018-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181126_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='publish_date',
            field=models.DateTimeField(default='2018-11-26 18:25:23'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='article_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img_url',
            field=models.TextField(),
        ),
    ]
