# Generated by Django 2.1.2 on 2018-11-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181110_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='user_id',
            new_name='author',
        ),
    ]
