# Generated by Django 2.1.2 on 2018-11-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181104_0957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('industry_name', 'sub_industry_name')},
        ),
    ]
