# Generated by Django 2.1.2 on 2018-11-04 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181104_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together=set(),
        ),
    ]
