# Generated by Django 2.1.2 on 2018-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181104_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('woman', '女'), ('other', '其他')], default=('男',), max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
