# Generated by Django 2.1.3 on 2018-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181201_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='publish_date',
            field=models.DateTimeField(default='2018-12-01 17:42:58'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='article_url',
            field=models.IntegerField(),
        ),
    ]
