# Generated by Django 2.1.3 on 2018-12-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181201_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='wechatarticle',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.DeleteModel(
            name='BlogArticle',
        ),
    ]
