# Generated by Django 2.1.3 on 2018-12-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181203_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
                ('publish_date', models.DateTimeField(default='2018-12-03 16:27:09')),
                ('cover_img', models.TextField()),
                ('article_html', models.TextField()),
                ('img_amount', models.IntegerField(default='0')),
                ('word_amount', models.IntegerField(default='0')),
                ('video_amount', models.IntegerField(default='0')),
                ('audio_amount', models.IntegerField(default='0')),
                ('browsed_times', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
