# Generated by Django 2.1.3 on 2018-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181209_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
