# Generated by Django 2.1.3 on 2018-12-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181209_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogArticle',
        ),
    ]
