# Generated by Django 2.1.3 on 2018-12-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_blogarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examine', models.BooleanField(default=False)),
                ('pass_or_not', models.BooleanField(default=False)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BlogArticle')),
            ],
        ),
    ]
