# Generated by Django 2.1.3 on 2018-12-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_onwall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='onwall',
            name='article',
        ),
        migrations.DeleteModel(
            name='BlogArticle',
        ),
        migrations.DeleteModel(
            name='OnWall',
        ),
    ]
