# Generated by Django 2.1.3 on 2018-12-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181211_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('cover_img', models.TextField()),
                ('article_html', models.TextField()),
                ('img_amount', models.IntegerField(default=0)),
                ('word_amount', models.IntegerField(default=0)),
                ('video_amount', models.IntegerField(default=0)),
                ('audio_amount', models.IntegerField(default=0)),
                ('browsed_times', models.PositiveIntegerField(default=0)),
                ('recommend', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category')),
                ('tags', models.ManyToManyField(blank=True, to='app.Tag')),
            ],
            options={
                'ordering': ('-publish_time',),
            },
        ),
        migrations.CreateModel(
            name='OnWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examine', models.BooleanField(default=False)),
                ('pass_or_not', models.BooleanField(default=False)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BlogArticle')),
            ],
        ),
    ]
